use data1;

/*JOINS:
"it is process of retriving data from multiple
tables simultanesouly is known as joins".

why should we use joins???
"whenever attributes/columns has to be selected
from both table we must use joins".

Types of joins
1)cartesian join/cross join
2)inner join/equi join
3)outer join
  1)left outer join
  2)Right outer join
  3)Full outer join
4)self join
5)Natural join

1)cartesian join/croos join:
"In cartesian join table1 records are merged with all the
records of table2".

syntax:ANSI
SELECT COLUMN_NAME1,COLUMN_NAME2.....COLUMN_NAMEN
FROM TABLE_NAME1 CROSS JOIN TABLE_NAME2;
*/
SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT ENAME,loc
FROM EMP CROSS JOIN DEPT;

/*INNER JOIN/EQUI JOIN:
"IT IS USED TO OBTAIN ONLY MATCHING RECORDS OR RECORDS WHICH
HAS PAIR".
 
JOIN CONDITION:
"IT IS CONDITION ON WHICH TWO OR MORE TABLES JOINED 
TOGETHER".

SYNTAX:
TABLE_NAME1.COLUMN_NAME=TABLE_NAME2.COLUMN_NAME;
EMP.DEPTNO=DEPT.DEPTNO

SYNTAX:INNER JOIN(ANSI)
SELECT COLUMN_NAME1,COLUMN_NAME2....COLUMN_NAMEN
FROM TABLE_NAME1 INNER JOIN TABLE_NAME2
ON <JOIN CONDITION>;
*/
SELECT ENAME,LOC
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO;

/*WAQTD ENAME,SALARY &DNAME OF EMPLOYEE*/
SELECT ENAME,SAL,DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO;

/*WAQTD NAME,JOB,DNAME,LOCATION OF EMPLOYEE IF EMPLOYEE
IS WORKING AS ANALYST*/
SELECT ENAME,JOB,DNAME,LOC
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE JOB IN('ANALYST');

/*WAQTD DEATAILS OF EMPLOYEE TABLE,DETAILS OF DEPARTMENT TABLE
IF EMPLOYEE NAME STARTS WITH A AND ENDS WITH N */
SELECT *
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE ENAME LIKE 'A%N';

/*WAQTD NAME,SAL,HIREDATE,LOCATION OF EMPLOYEE IF EMPLOYEE
IS GETTING SALARY MORE THAN 2000 AND WORKING IN DEPTNO
20 OR 30 AS MANAGER OR SALESMAN*/
SELECT ENAME,SAL,HIREDATE,loc
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE SAL>2000 AND EMP.DEPTNO IN(20,30) 
AND JOB IN('MANAGER','SALESMAN');

/*WAQTD DETAILS OF EMPLOYEE ALONG WITH LOCATION IF EMPLOYEE
WORKING IN SAME DEPTNO AS JONES AND WORKING IN DEPTNO 20 OR 30*/
SELECT EMP.*,loc
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE EMP.DEPTNO=(SELECT EMP.DEPTNO
                   FROM EMP
                   WHERE ENAME='JONES') AND EMP.DEPTNO IN(20,30);
                   
/*WAQTD NAME,SALARY,JOB,HIREDATE,DNAME,LOCATION OF EMPLOYEE
IF EMPLOYEE IS HIRED AFTER ALLEN BUT BEFORE SCOTT AND WORKING AS
 MANAGER OR SALESMAN OR CLERK AND THEIR NAME SHOULD HAVE EXACTLY FOUR
 CHARACTERS &GETTING SALARY MORE THAN 1000*/
 SELECT ENAME,SAL,JOB,HIREDATE,DNAME,loc
 FROM EMP INNER JOIN DEPT
 ON EMP.DEPTNO=DEPT.DEPTNO
 WHERE HIREDATE>(SELECT HIREDATE
                 FROM EMP
                 WHERE ENAME='ALLEN') AND HIREDATE<(SELECT HIREDATE
                                                    FROM EMP
                                                    WHERE ENAME='SCOTT')
AND JOB IN ('MANAGER','SALESMAN','CLERK') AND ENAME LIKE '____' AND SAL>1000;

/*NATURAL JOIN:
"it behaves as inner join if there is relationship between two tables. else
if there is no relationship between two tables it behaves as cartesian join/cross join".

syntax:ansi
select column_name1,column_name2.......column_namen
from table_name1 natural join table_name2;
*/