use data1;

select * from emp;

-- WAQTD THE ANNUAL SALARY OF THE EMPLOYEE WHOSE NAME IS SMITH.
SELECT ENAME,12*SAL AS ANNUAL_SALARY
FROM EMP
WHERE ENAME = "SMITH";

-- 2.WAQTD NAME OF THE EMPLOYEES WORKING AS CLERK.
SELECT ENAME, JOB
FROM EMP
WHERE JOB = "CLERK";

-- 3.WAQTD SALARY OF THE EMPLOYEES WHO ARE WORKING AS SALESMAN.
SELECT ENAME ,SAL,JOB
FROM EMP
WHERE JOB = 'SALESMAN';

-- 4.WAQTD DETAILS OF THE EMP WHO EARNS MORE THAN 2000.
SELECT * 
FROM EMP
WHERE SAL >2000;

-- 5.WAQTD DETAILS OF THE EMP WHOS NAME IS JONES.
SELECT *
FROM EMP
WHERE ENAME = "JONES";

-- 6.WAQTD DETAILS OF THE EMP WHO WAS HIRED AFTER 01-JAN-81.
SELECT * 
FROM EMP
WHERE HIREDATE > '1981-01-01';

/* 7.WAQTD NAME AND SAL ALONG WITH HIS ANNUAL 
SALARY IF THE ANNUAL SALARY IS MORE THAN 12000. */

SELECT ENAME,SAL,12*SAL
FROM EMP
WHERE 12*SAL > 12000;

-- 8.WAQTD EMPNO OF THE EMPLOYEES WHO ARE WORKING IN DEPT 30.
SELECT EMPNO, DEPTNO
FROM EMP
WHERE DEPTNO = 30;

-- 9.WAQTD ENAME AND HIREDATE IF THEY ARE HIRED BEFORE 1981.
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE < '1981-01-01';

-- 10.WAQTD DETAILS OF THE EMPLOYEES WORKING AS MANAGER.
SELECT *
FROM EMP
WHERE JOB = 'MANAGER';

-- 11.WAQTD NAME AND SALARY GIVEN TO AN EMPLOYEE IF EMPLOYEE EARNS A COMMISSION OF RUPEES 1400.
SELECT ENAME, SAL, COMM
FROM EMP
WHERE COMM = 1400;

-- 12.WAQTD DETAILS OF EMPLOYEES HAVING COMMISSION MORE THAN SALARY.
SELECT * 
FROM EMP 
WHERE COMM > SAL ;

-- 13.WAQTD EMPNO OF EMPLOYEES HIRED BEFORE THE YEAR 87.
SELECT EMPNO ,HIREDATE
FROM EMP 
WHERE HIREDATE < '1987-01-01';

-- 14.WAQTD DETAILS OF EMPLOYEES WORKING AS AN  ANALYST
SELECT * 
FROM EMP
WHERE JOB = 'ANALYST';

-- 15.WAQTD DETAILS OF EMPS EARNING MORE THAN 2000 RUPEES PER MONTH
SELECT * 
FROM EMP
WHERE SAL >2000;

-- LOGICAL OPERATOR QUESTIONS.

--  1)	WAQTD name and deptno along with job for the employee working in dept 10 .
SELECT ENAME,DEPTNO,JOB
FROM EMP
WHERE DEPTNO =10;

-- 2)	WAQTD name and deptno along with job for the employee working as manager in dept 10
SELECT ENAME,DEPTNO, JOB
FROM EMP
WHERE JOB ='MANAGER' AND DEPTNO = 10;

-- 3)	WAQTD name , deptno , salary of the employee working in dept 20 and earning less than 3000
SELECT ENAME ,DEPTNO,SAL
FROM EMP
WHERE DEPTNO =20 AND SAL<3000;

-- 4)	WAQTD name and salary of the employee if emp earns More than 1250 but less than 3000 .
SELECT ENAME , SAL 
FROM EMP
WHERE SAL>1250 AND SAL <3000;

-- 5)	WAQTD name and deptno of the employees if the works in dept 10 or 20 .
SELECT ENAME, DEPTNO
FROM EMP
WHERE DEPTNO = 10 OR DEPTNO= 20;

/* 6)	WAQTD name and sal and deptno of the employees
 If emp gets more than 1250 but less than 4000 and works in dept 20 .*/
 
 SELECT ENAME ,SAL, DEPTNO
 FROM EMP
 WHERE SAL>1250 AND SAL<4000 AND DEPTNO =20;

-- 7)	WAQTD name , job , deptno of the employees working as a manager in dept 10 or 30 .
SELECT ENAME, JOB, DEPTNO
FROM EMP
WHERE JOB ='MANAGER' AND (DEPTNO=10 OR DEPTNO=20);

-- 8)	WAQTD name , deptno , job of the employees working in dept 10 or 20 or 30 as a clerk .
SELECT ENAME, DEPTNO, JOB
FROM EMP
WHERE JOB ='CLERK';

-- 9)	WAQTD name , job and deptno of the employees working as clerk or manager in dept 10 .
SELECT ENAME, JOB, DEPTNO
FROM EMP
WHERE (JOB = 'CLERK' OR JOB ='MANAGER') AND DEPTNO =10;