use MYDATA;

SELECT * FROM EMP;

-- ASSIGNMENT ON SEPCIAL OPERATORS :

-- 1)	LIST ALL THE EMPLOYEES WHOSE COMMISSION IS NULL
SELECT ENAME,COMM
FROM EMP
WHERE COMM IS NULL;

-- 2)	LIST ALL THE EMPLOYEES WHO DON’T HAVE A REPORTING MANAGER
SELECT ENAME
FROM EMP
WHERE MGR IS NULL;

-- 3)	LIST ALL THE SALESMEN IN DEPT 30
SELECT ENAME,JOB
FROM EMP
WHERE JOB ='SALESMAN' AND DEPTNO =30;

-- 4)	LIST ALL THE SALESMEN IN DEPT NUMBER 30 AND HAVING SALARY GREATER THAN 1500
SELECT *
FROM EMP
WHERE DEPTNO=30 AND SAL >1500;

-- 5)	LIST ALL THE EMPLOYEES WHOSE NAME STARTS WITH ‘S’ OR ‘A’
SELECT ENAME
FROM EMP
WHERE ENAME LIKE 'S%' OR ENAME LIKE 'A%';
-- WHERE ENAME IN('S%','A%');   (WRONG)

-- 6)	LIST ALL THE EMPLOYEES EXCEPT THOSE WHO ARE WORKING IN DEPT 10 & 20.
SELECT ENAME ,DEPTNO
FROM EMP
WHERE DEPTNO NOT IN(10,20);

-- 7)	LIST THE EMPLOYEES WHOSE NAME DOES NOT START WITH ‘S’
SELECT ENAME 
FROM EMP
WHERE ENAME NOT LIKE 'S%';

-- 8)	LIST ALL THE EMPLOYEES WHO ARE HAVING REPORTING MANAGERS IN DEPT 10
SELECT *
FROM EMP
WHERE MGR IS NOT NULL AND DEPTNO =10;

-- 9)	LIST ALL THE EMPLOYEES WHOSE COMMISSION IS NULL AND WORKING AS CLERK
SELECT *
FROM EMP
WHERE COMM IS NULL AND JOB = 'CLERK';

-- 10)	LIST ALL THE EMPLOYEES WHO DON’T HAVE A REPORTING MANAGER IN DEPTNO 10 OR 30.
SELECT *
FROM EMP
WHERE MGR IS NULL AND DEPTNO IN(10,30);

-- 11)	LIST ALL THE SALESMEN IN DEPT 30 WITH SAL MORE THAN 2450
SELECT * 
FROM EMP
WHERE DEPTNO =30 AND SAL >2450;

-- 12)	LIST ALL THE ANALYST IN DEPT NUMBER 20 AND HAVING SALARY GREATER THAN 2500
SELECT * 
FROM EMP
WHERE JOB = 'ANALYST' AND DEPTNO =20 AND SAL >2500;

-- 13)	LIST ALL THE EMPLOYEES WHOSE NAME STARTS WITH ‘M’ OR ‘J’
SELECT *
FROM EMP
WHERE ENAME LIKE 'M%' OR ENAME LIKE "J%";

-- 14)	LIST ALL THE EMPLOYEES WITH ANNUAL SALARY EXCEPT THOSE WHO ARE WORKING IN DEPT 30
SELECT ENAME,12*SAL AS ANNUAL_SAL,DEPTNO
FROM EMP
WHERE DEPTNO NOT IN(30);

-- 15)	LIST THE EMPLOYEES WHOSE NAME DOES NOT END WITH ‘ES’ AND ‘R’
SELECT ENAME 
FROM EMP
WHERE ENAME NOT LIKE "%ES" AND ENAME NOT LIKE "%R";

 SELECT ENAME 
FROM EMP
WHERE ENAME LIKE "%ES" OR ENAME LIKE "%R";  
-- WHOSE END WITH 'ES' AND 'R'

-- 16)	LIST ALL THE EMPLOYEES WHO ARE HAVING REPORTING MANAGERS IN DEPT 10 ALONG WITH 10% HIKE IN SALARY
SELECT *, SAL+ 1/10*SAL
FROM EMP 
WHERE MGR IS NOT NULL AND DEPTNO IN (10);
-- WHERE MGR IS NOT NULL AND DEPTNO =10;

-- 17)	DISPLAY ALL THE EMPLOYEE WHO ARE ‘SALESMAN’S HAVING ‘E’ AS THE LAST BUT ONE CHARACTER IN ENAME.
SELECT ENAME 
FROM EMP
WHERE JOB ='SALESMAN' AND ENAME LIKE '%E_';

-- 18)	DISPLAY ALL THE EMPLOYEE WHO ARE JOINED AFTER YEAR 81.
SELECT ENAME, HIREDATE
FROM EMP 
WHERE HIREDATE > '1981-12-31';

-- 19)	DISPLAY ALL THE EMPLOYEE WHO ARE JOINED  DURING 1982. 
SELECT ENAME,HIREDATE
FROM EMP
WHERE HIREDATE BETWEEN '1982-01-01' AND '1982-12-31';

-- 20)	LIST THE EMPLOYEES WHO ARE NOT WORKING AS MANAGERS AND CLERKS IN DEPT 10 AND 20 WITH A SALARY IN THE RANGE OF 1000 TO 3000.
SELECT *
FROM EMP
WHERE JOB!= 'MANAGER' AND JOB!= 'CLERK' AND DEPTNO NOT IN (10,20) AND SAL BETWEEN 1000 AND 3000;



