/*Specail Operators:
1)IN:
"IT IS A MULTIVALUED OPERATOR WHICH ACCEPTS MULTIPLE VALUES
AT RHS.
SYNTAX:COLUMN_NAME/EXPRESSION IN(V1,V2.......VN);

2)NOT IN:
"it is similar to IN operator instead of selecting values
values are getting rejected".
syntax:column_name/expression not in(v1,v2......vn);

3)BETWEEN
4)NOT BETWEEN
5)IS
6)IS NOT
7)LIKE 
8)NOT LIKE
*/
USE data1;

SELECT ENAME
FROM EMP
WHERE DEPTNO=10 OR DEPTNO=20 OR DEPTNO=30;

SELECT ENAME,DEPTNO
FROM EMP
WHERE DEPTNO IN(10,20,30);

/*WAQTD NAME &JOB OF EMPLOYEE IF EMPLOYEE IS WORKING AS
MANAGER OR SALESMAN OR ANALYTS*/
SELECT ENAME,JOB
FROM EMP
WHERE JOB IN('MANAGER','SALESMAN','ANALYST');
-- WHERE JOB='MANAGER' OR JOB='SALESMAN' OR JOB='ANALYST';

/*waqtd name &deptno of employee if employee is not working
in deptno 20 &30*/
select ename,deptno
from emp
where deptno not in(20,30);
-- where deptno!=20 and deptno!=30;

select ename,job
from emp
where job!='manager' and job!='analyst' and job!='president';
-- where job not in ('manager','analyst','president');

/*WAQTD NAME &HIREDATE OF EMPLOYEE IF EMPLOYEE IS HIRED
DURING 1981*/
SELECT ENAME,HIREDATE
FROM EMP
WHERE HIREDATE BETWEEN '1981-01-01' AND '1981-12-31';
-- WHERE HIREDATE>='1981-01-01' AND HIREDATE<='1981-12-31';


/*BETWEEN:
"IT IS USED TO SELECT THE RANGE OF VALUES".
SYNTAX:
COLUMN_NAME BETWEEN 'LOWER_RANGE' AND 'HIGHER_RANGE';
*/

/*WAQTD NAME &SALARY OF EMPLOYEE IF EMPLOYEE IS GETTING
A SALARY IN THE RANGE OF 3000 AND 1000*/
SELECT ENAME,SAL
FROM EMP
WHERE SAL BETWEEN 1000 AND 3000;

/*WAQTD NAME &SALARY OF EMPLOYEE IF EMPLOYEE IS GETTING
SALARY BETWEEN 2000 AND 3000*/
SELECT ENAME,SAL
FROM EMP
WHERE SAL BETWEEN 2001 AND 2999;

/*WAQTD NAME &SALARY OF EMPLOYEE IF EMPLOYEE IS GETTING
SALARY IN THE RANGE BETWEEN 1000 AND 2000*/
SELECT ENAME,SAL
FROM EMP
WHERE SAL BETWEEN 1001 AND 1999;

/*WAQTD NAME &HIREDATE OF EMPLOYEE IF EMPLOYEE IS HIRED BETWEEN
'1981-01-01' AND '1981-12-31'*/
SELECT ENAME,HIREDATE
FROM EMP
WHERE HIREDATE BETWEEN '1981-01-02' AND '1981-12-30';


/*NOT BETWEEN:
"OPPOSITE OF BETWEEN OPERATOR".
SYNTAX: COLUMN_NAME NOT BETWEEN 'LOWER_RANGE' AND 'HIGHER_RANGE'
*/

SELECT ENAME,HIREDATE
FROM EMP
WHERE HIREDATE NOT BETWEEN '1981-01-01' AND '1981-12-31';

/*WATQD NAME &SALARY OF EMPLOYEE IF EMPLOYEE IS NOT GETTING
SALARY BETWEEN 1000 AND 3000*/
SELECT ENAME,SAL
FROM EMP
WHERE SAL NOT BETWEEN 1001 AND 2999;

/*WAQTD NAME &SALARY OF EMPLOYEE IF EMPLOYEE IS NOT GETTING
SALARY IN THE RANGE OF 1000 AND 3000*/
SELECT ENAME,SAL
FROM EMP
WHERE SAL NOT BETWEEN 1000 AND 3000;

SELECT * FROM EMP;

UPDATE EMP
SET COMM=500
WHERE ENAME='TURNER';

SELECT ENAME,COMM
FROM EMP
WHERE COMM IS NULL;

SELECT ENAME,SAL
FROM EMP
WHERE SAL IS NULL;


/*IS:
"IT IS USED TO COMPARE WITH NULL VALUES"
SYNATX:COLUMN_NAME/EXPRESSION IS NULL;
*/

/*IS NOT:
"IT IS USED TO COMPARE WITH NOT NULL VALUES"
SYNTAX:COLUMN_NAME/EXPRESSION IS NOT NULL*/

/*WAQTD NAME &COMMISSION OF EMPLOYEE IF EMPLOYEE IS GETTING
COMMISSION*/
SELECT ENAME,COMM
FROM EMP
WHERE COMM IS NOT NULL;


/*LIKE:
"IT IS USED FOR PATTERN MATCHING PURPOSE".
->TO ACHIVE THIS PATTERN MATCHING WE REQUIRED 2 SYMBOLS.
1)%
2)_
SYNTAX:COLUMN_NAME LIKE 'PATTERN_TO_MATCH';
*/

/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE NAME STARTS WITH A*/
SELECT ENAME
FROM EMP
WHERE ENAME LIKE 'A%';

/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE NAME ENDS WITH N*/
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '%N';

/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE NAME STARTS WITH
J AND ENDS WITH CHARACTER S*/
SELECT ENAME
FROM EMP
WHERE ENAME LIKE 'J%%S';
-- WHERE ENAME LIKE 'J%S';
-- WHERE ENAME LIKE 'J%' AND ENAME LIKE '%S';

/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE NAME HAS A CHARACTER L IN
THEIR NAME*/
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '%L%';

/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE NAME HAS 4 CHARACTERS*/
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '____';

/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE NAME'S 2ND CHARCATER STARTS
WITH A*/
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '_A%';

/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE NAME'S 3RD CHARCTER STARTS
WITH L*/
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '__L%';

/*WAQTD NAME OF EMPLOYEE IF EMPLOYEE NAME STARTS WITH VOWELS
(AEIOU)*2023 CONG,2024 MICROSOFT,IBM*/
SELECT ENAME 
FROM EMP
WHERE ENAME LIKE 'A%' OR ENAME LIKE 'E%' OR ENAME LIKE'I%'
OR ENAME LIKE 'O%' OR ENAME LIKE 'U%';

/*WAQTD NAME OF EMPLOYEE WHICH DOES NOT START WITH VOWELS*/
SELECT ENAME
FROM EMP
WHERE ENAME NOT LIKE 'A%' AND ENAME NOT LIKE 'E%' AND
ENAME NOT LIKE 'I%' AND ENAME NOT LIKE 'O%' AND ENAME NOT LIKE
'U%';