use mydata;

-- 1.	WAQTD NUMBER OF EMPLOYEES GETTING SALARY LESS THAN 2000 IN DEPTNO 10
SELECT COUNT(*)
FROM EMP
WHERE SAL<2000 AND DEPTNO =10;

-- 2.	WAQTD TOTAL SALARY NEEDED TO PAY EMPLOYEES WORKING AS CLERK
SELECT SUM(SAL)
FROM EMP
WHERE JOB = 'CLERK';

-- 3.	WAQTD AVERAGE SALARY NEEDED TO PAY ALL EMPLOYEES
SELECT AVG(SAL)
FROM EMP;

-- 4.	WAQTD NUMBER OF EMPLOYEES HAVING 'A' AS THEIR FIRST CHARACTER
SELECT COUNT(*)
FROM EMP
WHERE ENAME LIKE "A%";

SELECT * FROM EMP;

-- 5.	WAQTD NUMBER OF EMPLOYEES WORKING AS CLERK OR MANAGER
SELECT COUNT(ENAME)
FROM EMP
WHERE JOB IN('CLERK','MANAGER');

-- 6.	WAQTD TOTAL SALARY NEEDED TO PAY EMPLOYEES HIRED IN FEB
SELECT SUM(SAL)
FROM EMP 
WHERE HIREDATE = '%-02-%';
-- WRONG

SELECT SUM(SAL)
FROM EMP 
WHERE EXTRACT(MONTH FROM HIREDATE)=02;

-- 7.	WAQTD NUMBER OF EMPLOYEES REPORTING TO 7839 (MGR)
SELECT COUNT(*)
FROM EMP 
WHERE MGR = 7839 ;

-- 8.	WAQTD NUMBER OF EMPLOYEES GETTING COMISSION IN DEPTNO 30
SELECT COUNT(ENAME)
FROM EMP
WHERE COMM IS NOT NULL AND DEPTNO = 30;

-- 9.	WAQTD AVG SAL , TOTAL SAL , NUMBER OF EMPS AND MAXIMUM SALARY GIVEN TO EMPLOYEES WORKING AS PERSIDENT
SELECT AVG(SAL),SUM(SAL),COUNT(*),MAX(SAL)
FROM EMP
WHERE JOB ='PRESIDENT';

SELECT * FROM EMP;

-- 10.	WAQTD NUMBER OF EMPLOYEES HAVING 'A' IN THEIR NAMES
SELECT COUNT(*)
FROM EMP
WHERE ENAME LIKE'%A%';

use mydata;

-- 11.	WAQTD NUMBER OF EMPS AND TOTAL SALARY NEEDED TO PAY THE EMPLOYEES WHO HAVE 2 CONSICUTIVE L's IN THEIR NAMES
SELECT COUNT(*),SUM(SAL)
FROM EMP
WHERE ENAME LIKE "%LL%";

-- 12.	WAQTD NUMBER OF DEPARTMENTS PRESENT IN EMPLOYEE TABLE
SELECT distinct job 
FROM EMP;







